image: node:14.0.0

pipelines:
  default:
    - step:
        name: Test
        caches:
          - node
        script:
          - yarn
          - yarn test
  branches:
    staging:
      - step:
          name: Test
          caches:
            - node
          script:
            - yarn
            - yarn test
      - step:
          name: Deploy staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git staging:master
    master:
      - step:
          name: Test
          caches:
            - node
          script:
            - yarn
            - yarn test
      - step:
          name: Deploy production
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PRODUCTION.git master:master
