image: node:lts

pipelines:
  custom:
    deploy:
      - step:
          name: Deploy
          deployment: test
          caches:
            - node
          script:
            - apt-get update && apt-get install -y rsync
            - npm install && npm run build
            - ssh -p 2222 joshuaellis@162.241.194.68 mkdir /public_html/
            - rsync -az --delete ./build/ joshuaellis@162.241.194.68:2222/public_html/
