version: 2
jobs:
  build:
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  deploy:
      machine:
        enabled: true
      steps:
        - run:
            name: Build
            command: npm run build
        - run:
            name: Deploy
            command: |
              scp -P 2222 -r build/* $SSH_USER@$SSH_HOST:/public_html

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
            - build
          filters:
            branches:
              only: master

